const nodemailer = require('nodemailer');

const sendWelcomeEmail = async (targetEmail, couponCode, discount) => {
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // true for port 465 (SSL)
    auth: {
      user: process.env.MAIL_USERNAME, 
      pass: process.env.MAIL_PASSWORD  
    },
    tls: {
      rejectUnauthorized: false
    }
  });

  const mailOptions = {
    from: `"Habesha Wear Market" <${process.env.MAIL_USERNAME}>`,
    to: targetEmail,
    subject: 'Welcome to the Family! | የቅናሽ ኩፖንዎ እዚህ አለ!',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e1e1e1; border-radius: 15px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05);">
        <div style="background: linear-gradient(to right, #f97316, #f59e0b); padding: 30px; text-align: center; color: white;">
          <h1 style="margin: 0; font-size: 24px;">Thank You for Subscribing!</h1>
          <h2 style="margin: 5px 0 0 0; font-size: 20px; font-weight: normal;">ስለተመዘገቡ እናመሰግናለን!</h2>
        </div>
        <div style="padding: 30px; text-align: center; background-color: #ffffff;">
          <p style="color: #4b5563; font-size: 16px; line-height: 1.6;">
            Here is your exclusive welcome gift code. Use this at your checkout to claim your special reduction on authentic traditional & modern garments:
          </p>
          
          <!-- THIS INJECTS THE ACTUAL CODE GENERATED BY THE USER SUBSCRIPTION -->
          <div style="background-color: #f3f4f6; border: 2px dashed #f97316; display: inline-block; padding: 15px 40px; margin: 20px 0; border-radius: 10px;">
            <span style="font-size: 26px; font-weight: 900; color: #f97316; letter-spacing: 2px;">${couponCode}</span>
          </div>
          
          <p style="color: #111827; font-weight: bold; font-size: 18px;">Get ${discount}% OFF your first order!</p>
          <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 30px 0;" />
          <p style="color: #9ca3af; font-size: 12px;">This coupon belongs exclusively to ${targetEmail} and is valid for 30 days.</p>
        </div>
      </div>
    `
  };

  const info = await transporter.sendMail(mailOptions);
  return info;
};

module.exports = { sendWelcomeEmail };